"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css';
import 'react-toastify/dist/ReactToastify.css';


import { createContext, useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const store = createContext(null)

export default function RootLayout({ children }) {

//   const [agreement, setAgreement] = useState({
//     // agreement:[],
//     agreement:[],
//     // client:[]
// 
//   });
// 
//   useEffect(() => {
//     const getData = async () => {
//       try {
//         const agreement = await getAgreement();
//         // const client=await getClient()
//         // console.log("layout page ",Admin)
//         setAgreement({...agreement,agreement})
// 
//       } catch (error) {
//         console.log(error)
//       }
//     }
//     getData()
// 
//   }, [])


  return (
    // <store.Provider value={[agreement, setAgreement]}>
    <html lang="en">

      <body className={inter.className} suppressHydrationWarning>
        {/* <Navbar/> */}
        <ToastContainer />
        {children}

      </body>
    </html>
    // </store.Provider>
  )
}
